spring.application.name=MobileRechargePrepaid

server.port=8081

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noorulbashri241@gmail.com
spring.mail.password=cdgrjonbheriioub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mysql://localhost:3306/mobilePrepaidDb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=yourSuperLongRandomSecretThatIsAtLeast64CharactersLongForHS512AlgorithmExample1234567890
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

twilio.account.sid=ACc3f77cf7467229f0c6f09227cde1975b
twilio.auth.token=c03c1844ae92d59ee0ba569aad507d20
twilio.phone.number=+12692846179

razorpay.key.id=rzp_test_spaeoXaSD8ACMW

razorpay.key.secret=JnbOjJ6LNxcYhaDqHXbTZmaE